title: Nqd8VId6
#author: GitHub User
email: None
description: > # this means to ignore newlines until "show_exerpts:"
  my blog
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""
url: "https://citrusice.github.io"
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
exclude: [makefile,newpost.sh,Gemfile,Gemfile.lock,LICENSE.txt,README.md,screen1.png,screen2.png,texture.gemspec]
permalink: /posts/:title/
texture:
  title: Nqd8VId6
  tagline: Developer. Security Researcher
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  CitrusIce
    #linkedIn: in/thelehhman
    rss: "/feed.xml"
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed