title: Nqd8VId6
#author: GitHub User
email: None
description: > # this means to ignore newlines until "show_exerpts:"
  my blog
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: ""
url: "https://citrusice.github.io"
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
exclude: [makefile,newpost.sh,Gemfile,Gemfile.lock,LICENSE.txt,README.md,screen1.png,screen2.png,texture.gemspec]
permalink: /posts/:title/
texture:
  title: Nqd8VId6
  tagline: Developer. Security Researcher
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  CitrusIce
    #linkedIn: in/thelehhman
    rss: "/feed.xml"
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed

# 图片本地化插件配置
image_localizer:
  enabled: true                # 是否启用插件
  image_dir: 'assets/images'   # 图片保存目录
  process_pages: true          # 是否处理页面
  process_posts: true          # 是否处理文章
  fix_existing_paths: true     # 是否修复已存在的本地图片路径
  copy_local_images: true      # 是否复制本地绝对路径的图片
  skip_patterns:               # 跳过的URL模式（正则表达式）
    - '^data:'                 # 跳过 data URL

# 确保图片目录被包含在构建中
include:
  - assets/images